import csv
import io
from fpdf import FPDF

class AttendancePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Attend-X Attendance Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by Attend-X System', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_attendance_csv(records):
    """
    Generate CSV data from attendance records.
    """
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['Student Name', 'Roll Number', 'Date', 'Status', 'Confidence %', 'Verified'])
    
    for r in records:
        # Assuming records were fetched with .select("*, students(*)")
        student = r.get('students', {})
        writer.writerow([
            student.get('name', 'N/A'),
            student.get('roll_number', 'N/A'),
            r.get('date'),
            r.get('status'),
            f"{r.get('confidence', 0)}%",
            'Yes' if r.get('verified') else 'No'
        ])
    
    return output.getvalue()

def generate_attendance_pdf(records):
    """
    Generate PDF binary data from attendance records.
    """
    pdf = AttendancePDF()
    pdf.add_page()
    
    # Table Header
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(45, 10, 'Name', 1, 0, 'C', True)
    pdf.cell(35, 10, 'Roll No', 1, 0, 'C', True)
    pdf.cell(30, 10, 'Date', 1, 0, 'C', True)
    pdf.cell(25, 10, 'Status', 1, 0, 'C', True)
    pdf.cell(25, 10, 'Conf %', 1, 0, 'C', True)
    pdf.cell(25, 10, 'Verified', 1, 1, 'C', True)
    
    # Table Content
    pdf.set_font('Arial', '', 9)
    for r in records:
        student = r.get('students', {})
        # Truncate long names to fit
        name = str(student.get('name', 'N/A'))[:25]
        roll = str(student.get('roll_number', 'N/A'))[:15]
        
        pdf.cell(45, 10, name, 1)
        pdf.cell(35, 10, roll, 1)
        pdf.cell(30, 10, str(r.get('date')), 1)
        pdf.cell(25, 10, str(r.get('status')), 1)
        pdf.cell(25, 10, f"{r.get('confidence', 0)}%", 1)
        pdf.cell(25, 10, 'Yes' if r.get('verified') else 'No', 1, 1)
        
    return pdf.output(dest='S').encode('latin-1')
